### ISSUE TITLE
Multiple Trash Pickups

### ISSUE THREAD

**Issue by thordy** [jonkristian/wasteplan_trv#15]
Hi,

Thanks for creating this integration, it's really useful!
I do have a question though, on how it handles when there are multiple pickups on the same day.

As you can see, tomorrow there will be two pickups `Plastemballasje` and `Matavfall`
![image](https://github.com/jonkristian/wasteplan_trv/assets/1622278/73c9a600-d0c5-44d2-a6fe-09c75bcac8e0)

This also shows correctly in the `Calendar` in HA
![image](https://github.com/jonkristian/wasteplan_trv/assets/1622278/0bb2e2dd-33dc-46f3-8065-6d56f4ea1ddf)

But when I look at the state of the sensor, it only shows one of them
![image](https://github.com/jonkristian/wasteplan_trv/assets/1622278/725db3e4-80b2-4694-93c0-0fad264708c7)

Now this might be a lack of HA knowledge on my part, but is there any way to get the `Matavfall` state as well?
It would be better in my opinion if the `message`  state of the sensor was something like `Plastemballasje & Matavfall`? 

I want to have certain alerting based on trash types but currently this won't work since I'm not able to know all the pickups which will happen

**Comment by thordy** [comment]
Spent some more time figuring out how I could solve this, and found a solution.
Added the following template sensor (to configuration)
``` 
- trigger:
    - platform: time_pattern
      hours: "/1"
  action:
    - service: calendar.get_events
      target:
        entity_id: calendar.tommeplan
      data:
        duration:
          days: 60
      response_variable: tommeplan
    - variables:
        all_events: "{{ tommeplan['calendar.tommeplan'].events  }}"
        matavfall: "{{ all_events | selectattr('summary', 'search', 'Matavfall', true) | list }}"
        restavfall: "{{ all_events | selectattr('summary', 'search', 'Restavfall', true) | list }}"
        pappogpapir: "{{ all_events | selectattr('summary', 'search', 'Papp og papir', true) | list }}"
        plastemballasje: "{{ all_events | selectattr('summary', 'search', 'Plastemballasje', true) | list }}"
        glassogmetall: "{{ all_events | selectattr('summary', 'search', 'Glass- og metallemballasje', true) | list }}"
  sensor:
    - name: Matavfall Henting
      unique_id: tommeplan_matavfall
      icon: mdi:trash-can-outline
      state: |
        {{ matavfall | count() }}
      attributes:
        scheduled_events: |
          {{ matavfall }}
        next_collection_date: |
          {{ (matavfall | first).start }}
        countdown: |
          {{ int((as_timestamp((matavfall | first).start) - as_timestamp(today_at('00:00')))/86400)}}

    - name: Restavfall Henting
      unique_id: tommeplan_restavfall
      icon: mdi:trash-can-outline
      state: |
        {{ restavfall | count() }}
      attributes:
        scheduled_events: |
          {{ restavfall }}
        next_collection_date: |
          {{ (restavfall | first).start }}
        countdown: |
          {{ int((as_timestamp((restavfall | first).start) - as_timestamp(today_at('00:00')))/86400)}}

    - name: Papp og Papir Henting
      unique_id: tommeplan_pappogpapir
      icon: mdi:trash-can-outline
      state: |
        {{ pappogpapir | count() }}
      attributes:
        scheduled_events: |
          {{ pappogpapir }}
        next_collection_date: |
          {{ (pappogpapir | first).start }}
        countdown: |
          {{ int((as_timestamp((pappogpapir | first).start) - as_timestamp(today_at('00:00')))/86400)}}

    - name: Plastemballasje Henting
      unique_id: tommeplan_plastemballasje
      icon: mdi:trash-can-outline
      state: |
        {{ plastemballasje | count() }}
      attributes:
        scheduled_events: |
          {{ plastemballasje }}
        next_collection_date: |
          {{ (plastemballasje | first).start }}
        countdown: |
          {{ int((as_timestamp((plastemballasje | first).start) - as_timestamp(today_at('00:00')))/86400)}}

    - name: Glass og Metall Henting
      unique_id: tommeplan_glassogmetall
      icon: mdi:trash-can-outline
      state: |
        {{ glassogmetall | count() }}
      attributes:
        scheduled_events: |
          {{ glassogmetall }}
        next_collection_date: |
          {{ (glassogmetall | first).start }}
        countdown: |
          {{ int((as_timestamp((glassogmetall | first).start) - as_timestamp(today_at('00:00')))/86400)}}
``` 

Which will give sensors like the following 
![image](https://github.com/jonkristian/wasteplan_trv/assets/1622278/80c5549d-e9ea-4fd9-8904-3fce002dd39a)

and with those I can create the automations I'm looking for.
